name: Deploy to EC2

on:
  push:
    branches:
      - main  # Trigger deploy on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Amazon ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1  # Update with your AWS region
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region $AWS_REGION
          docker login -u AWS -p $(aws ecr get-login-password --region us-east-1) 248189902622.dkr.ecr.us-east-1.amazonaws.com

      - name: Build Docker Image
        run: docker build -t node-retro-app .

      - name: Tag Docker Image for ECR
        run: docker tag node-retro-app:latest 248189902622.dkr.ecr.us-east-1.amazonaws.com/node-retro-app:latest

      - name: Push Docker Image to Amazon ECR
        run: docker push 248189902622.dkr.ecr.us-east-1.amazonaws.com/node-retro-app:latest

      - name: Deploy Docker Container to EC2
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          # Save the private key for SSH connection
          echo "$EC2_SSH_KEY" > ec2_ssh_key
          chmod 600 ec2_ssh_key

          # SSH into EC2 and log in to ECR, pull the latest image, then run it
          ssh -o StrictHostKeyChecking=no -i ec2_ssh_key ec2-user@$EC2_PUBLIC_IP << EOF
            # Configure AWS credentials on the EC2 instance
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set default.region us-east-1
            
            # Log in to ECR and pull the Docker image
            docker login -u AWS -p \$(aws ecr get-login-password --region us-east-1) 248189902622.dkr.ecr.us-east-1.amazonaws.com
            docker pull 248189902622.dkr.ecr.us-east-1.amazonaws.com/node-retro-app:latest
            
            # Stop and remove the current container, if it exists
            docker stop my-nodejs-app || true
            docker rm my-nodejs-app || true

            # Run the new container
            docker run -d -p 3000:3000 --name my-nodejs-app 248189902622.dkr.ecr.us-east-1.amazonaws.com/node-retro-app:latest
          EOF

      - name: Clean up
        run: rm -f ec2_ssh_key
