name: Deploy to EC2

on:
  push:
    branches:
      - main  # Trigger deploy on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Amazon ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1  # Update with your AWS region
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region $AWS_REGION
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 248189902622.dkr.ecr.us-east-1.amazonaws.com

      - name: Build Docker Image
        run: docker build -t my-nodejs-app .

      - name: Tag Docker Image for ECR
        run: docker tag my-nodejs-app:latest 248189902622.dkr.ecr.us-east-1.amazonaws.com/my-nodejs-app:latest

      - name: Push Docker Image to Amazon ECR
        run: docker push 248189902622.dkr.ecr.us-east-1.amazonaws.com/my-nodejs-app:latest

      - name: Deploy to EC2
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
        run: |
          # Save the private key for SSH connection
          echo "$EC2_SSH_KEY" > ec2_ssh_key
          chmod 600 ec2_ssh_key

          # SSH into EC2 and pull the latest image, then run it
          ssh -o StrictHostKeyChecking=no -i ec2_ssh_key ec2-user@$EC2_PUBLIC_IP << 'EOF'
            docker pull 248189902622.dkr.ecr.us-east-1.amazonaws.com/my-nodejs-app:latest
            docker stop my-nodejs-app || true
            docker rm my-nodejs-app || true
            docker run -d -p 3000:3000 --name my-nodejs-app 248189902622.dkr.ecr.us-east-1.amazonaws.com/my-nodejs-app:latest
          EOF

      - name: Clean up
        run: rm -f ec2_ssh_key
